/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Island/palmeras2.glb';

export function Palmeras(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmeras_1.geometry}
        material={materials.Tronco}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmeras_2.geometry}
        material={materials.Hojas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmeras_3.geometry}
        material={materials.Flowers}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Palmeras_4.geometry}
        material={materials['grass ']}
      />
    </group>
  )
}

useGLTF.preload(Model)