/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Island/Rocas_Isla.glb';


export function Rocas(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rocks.geometry}
      material={materials.Rocks}
      position={[4.21, 4.025, -32.016]}
      rotation={[-0.775, -0.891, 2.411]}
      scale={2.681}
    />
  </group>
  )
}

useGLTF.preload(Model)
