/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/CastilloArena.glb';

export function CastilloArena(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <group position={[0,0,0]} scale={0.06}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castillo_de_arena_1.geometry}
          material={materials['Castillo 1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castillo_de_arena_2.geometry}
          material={materials['Castillo 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castillo_de_arena_3.geometry}
          material={materials['Castillo 3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Castillo_de_arena_4.geometry}
          material={materials['Castillo 4']}
        />
      </group>
    </group>
  )
}

useGLTF.preload(Model)

export default CastilloArena ;

