/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Concha.glb';


export function Concha(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Concha.geometry}
        material={materials.Concha}
        position={[0,0,0]}
        scale={0.06}
      />
    </group>
  )
}

useGLTF.preload(Model)
export default Concha;