/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/EstrellaMar.glb';


export function EstrellaMar(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Estrella_de_mar.geometry}
        material={materials['Estrella de mar']}
        position={[0,0,0]}
        scale={0.12}

/>
    </group>
  )
}

useGLTF.preload(Model)
export default EstrellaMar;