/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Flores.glb';


export function Flores(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Canasta_1.geometry}
          material={materials.Canasta}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Canasta_2.geometry}
          material={materials.Flowers}
        />
      </group>
    </group>
  )
}

useGLTF.preload(Model)
export default Flores;