/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Hoguera.glb';


export function Hoguera(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={0.23}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vela001_1.geometry}
          material={materials.Vela}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vela001_2.geometry}
          material={materials.Rocks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vela001_3.geometry}
          material={materials.tronco}
        />
      </group>
    </group>
  )
}

useGLTF.preload(Model)
export default Hoguera;