/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import libroModel from '../../assets/preview/Achivements/Libro.glb';
export function Libro(props) {
  const { nodes, materials } = useGLTF(libroModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Libro.geometry}
        material={materials.Libro}
        position={[0, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(libroModel)

export default Libro;
