/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import paletaModel from '../../assets/preview/Achivements/Paleta.glb';
export function Paleta(props) {
  const { nodes, materials } = useGLTF(paletaModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paleta.geometry}
        material={materials.Paleta}
        scale={0.134}
        position={[0,-0.2,0]}
      />
    </group>
  )
}

useGLTF.preload(paletaModel)
export default Paleta;
