/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Panal.glb';


export function Panal(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Panal_de_abejas.geometry}
        material={materials['Panal de abejas']}
        position={[0,0,0]}
        scale={0.2}
      />
    </group>
  )
}

useGLTF.preload(Model)
export default Panal;


