/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import pastelModel from '../../assets/preview/Achivements/Pastel.glb';

export function Pastel(props) {
  const { nodes, materials } = useGLTF(pastelModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pastel.geometry}
        material={materials.Pastel}
        position={[0,0.5,0]}
        scale={0.1}
      />
    </group>
  )
}

useGLTF.preload(pastelModel)
export default Pastel;
