/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import relojModel from '../../assets/preview/Achivements/reloj.glb';


export function Reloj(props) {
  const { nodes, materials } = useGLTF(relojModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Reloj.geometry}
        material={materials.Reloj}
        scale={0.1}
        position={[0,0.5,0]}
      />
    </group>
  )
}

useGLTF.preload(relojModel)
export default Reloj;
