/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Tea.glb';

export function Tea(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tasa_de_te.geometry}
        material={materials['Tasa de te']}
        position={[0, 0, 0]}
        scale={0.05}
      />
    </group>
  )
}

useGLTF.preload(Model)
export default Tea;

