
/*Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Tronco.glb';

export function Tronco(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={0.08} rotation={[0,0 ,0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tronco_1.geometry}
          material={materials.Hongos}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tronco_2.geometry}
          material={materials.Tronco}
        />
      </group>
    </group>
  )
}

useGLTF.preload(  Model)
export default Tronco;


