/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Vela.glb';

export function Vela(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null}>
    <group position={[0, 0.5, 0]} scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vela_1.geometry}
          material={materials.Fuego}
        />
        <mesh castShadow receiveShadow geometry={nodes.Vela_2.geometry} material={materials.Vela} />
      </group>
    </group>
  )
}

useGLTF.preload(Model)
export default Vela;  

