/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Model from '../../assets/preview/Achivements/Vela2.glb';

export function Vela(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group {...props} dispose={null} scale={1} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vela001.geometry}
        material={materials['Fuego.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vela001_1.geometry}
        material={materials['Vela.001']}
      />
    </group>
  )
}

useGLTF.preload(Model)
export default Vela;  

