/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import candleModel from '../assets/preview/Achivements/candle.glb';

export function Candle(props) {
  const { nodes, materials } = useGLTF(candleModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.candle.geometry}
        material={materials.tiny_treats_1}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload(candleModel)
export default Candle;
