/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Grasss from '../assets/preview/Grass.glb'
import { RigidBody } from '@react-three/rapier';

const Grass = (props) =>  {
  const { nodes, materials } = useGLTF(Grasss);
  return (
       <RigidBody type="fixed" colliders="trimesh">
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GrassPlatform_Cylinder001-Mesh'].geometry}
        material={materials.Dirt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['GrassPlatform_Cylinder001-Mesh_1'].geometry}
        material={materials.Grass}
      />
    </group>
    </RigidBody>
  )
}

useGLTF.preload(Grasss)
export default Grass;