/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-island-88765d3c5db349e59c39cf9f592eba17
Title: Fantasy_Island
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import {a} from '@react-spring/three'
import islandScene from '../assets/preview/Achivements/island.glb'
import { RigidBody } from '@react-three/rapier';


const Island = (props) => {
const islandRef = useRef();
  const { nodes, materials } = useGLTF(islandScene);
  return (
    <group {...props} dispose={null}>
        <RigidBody type="fixed" colliders="trimesh">
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Water.geometry}
        material={materials.WaterMaterial}
      />
      
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Terrain_1.geometry}
        material={materials.GrayIslandMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Terrain_2.geometry}
        material={materials.CoffeIstandMaterial}
      />
     
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Terrain_3.geometry}
        material={materials.GrassIslandMaterial}
      />
       </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_1.geometry}
        material={materials.LeavesMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_2.geometry}
        material={materials.RocksMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_3.geometry}
        material={materials['LeavesMaterial.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_4.geometry}
        material={materials['LeavesMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_5.geometry}
        material={materials['LeavesMaterial.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_6.geometry}
        material={materials.BonesMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_7.geometry}
        material={materials['RocksMaterial.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_8.geometry}
        material={materials.TreeMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_9.geometry}
        material={materials['RocksMaterial.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_10.geometry}
        material={materials.BarkMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_11.geometry}
        material={materials.PillarMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_12.geometry}
        material={materials['BarkMaterial.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_13.geometry}
        material={materials['RocksMaterial.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_14.geometry}
        material={materials['LeavesMaterial.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_15.geometry}
        material={materials.FlowerMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_16.geometry}
        material={materials.PinkMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_17.geometry}
        material={materials['FlowerMaterial.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_18.geometry}
        material={materials.FloweMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vegetation_19.geometry}
        material={materials.ButterMaterial}
      />
    </group>
  )
}

export default Island;