/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import popsicleModel from '../assets/preview/Achivements/popsicle.glb';

export function Popsicle(props) {
  const { nodes, materials } = useGLTF(popsicleModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh'].geometry}
        material={materials.mat18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.mat8}
      />
    </group>
  )
}

useGLTF.preload(popsicleModel)
export default Popsicle;
